In [2]:
 %matplotlib notebook
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
# variable to hold csv
file = 'Resources/us-states.csv'

# read the csv
df = pd.read_csv(file, encoding="ISO-8859-1")
df.head()

         date       state  fips  cases  deaths
0  2020-01-21  Washington    53      1       0
1  2020-01-22  Washington    53      1       0
2  2020-01-23  Washington    53      1       0
3  2020-01-24    Illinois    17      1       0
4  2020-01-24  Washington    53      1       0

In [7]:
# pull just the dates, deaths and state
death_df = df[['state','date','deaths']]
death_df

               state        date  deaths
0         Washington  2020-01-21       0
1         Washington  2020-01-22       0
2         Washington  2020-01-23       0
3           Illinois  2020-01-24       0
4         Washington  2020-01-24       0
...              ...         ...     ...
12714       Virginia  2020-10-19    3457
12715     Washington  2020-10-19    2357
12716  West Virginia  2020-10-19     399
12717      Wisconsin  2020-10-19    1624
12718        Wyoming  2020-10-19      57

[12719 rows x 3 columns]

In [58]:
date_state_death = death_df[death_df["date"] == '2020-10-19']
date_state_death_df = pd.DataFrame(date_state_death)
#date_state_death_df
covid_death_oct_nineteenth = date_state_death_df.set_index("state")
covid_death_oct_ninteenth_df = pd.DataFrame(covid_death_oct_nineteenth)
covid_death_oct_ninteenth_df

                                date  deaths
state
Alabama                   2020-10-19    2789
Alaska                    2020-10-19      63
Arizona                   2020-10-19    5830
Arkansas                  2020-10-19    1714
California                2020-10-19   16987
Colorado                  2020-10-19    2207
Connecticut               2020-10-19    4554
Delaware                  2020-10-19     666
District of Columbia      2020-10-19     641
Florida                   2020-10-19   16020
Georgia                   2020-10-19    7479
Guam                      2020-10-19      67
Hawaii                    2020-10-19     186
Idaho                     2020-10-19     535
Illinois                  2020-10-19    9520
Indiana                   2020-10-19    3960
Iowa                      2020-10-19    1548
Kansas                    2020-10-19     872
Kentucky                  2020-10-19    1381
Louisiana                 2020-10-19    5766
Maine                     2020-10-19     146
Maryland                  2020-10-19    4041
Massachusetts             2020-10-19    9753
Michigan                  2020-10-19    7364
Minnesota                 2020-10-19    2292
Mississippi               2020-10-19    3171
Missouri                  2020-10-19    2660
Montana                   2020-10-19     242
Nebraska                  2020-10-19     568
Nevada                    2020-10-19    1714
New Hampshire             2020-10-19     468
New Jersey                2020-10-19   16214
New Mexico                2020-10-19     935
New York                  2020-10-19   32990
North Carolina            2020-10-19    3969
North Dakota              2020-10-19     413
Northern Mariana Islands  2020-10-19       2
Ohio                      2020-10-19    5075
Oklahoma                  2020-10-19    1173
Oregon                    2020-10-19     630
Pennsylvania              2020-10-19    8562
Puerto Rico               2020-10-19     768
Rhode Island              2020-10-19    1159
South Carolina            2020-10-19    3661
South Dakota              2020-10-19     323
Tennessee                 2020-10-19    2896
Texas                     2020-10-19   17564
Utah                      2020-10-19     547
Vermont                   2020-10-19      58
Virgin Islands            2020-10-19      21
Virginia                  2020-10-19    3457
Washington                2020-10-19    2357
West Virginia             2020-10-19     399
Wisconsin                 2020-10-19    1624
Wyoming                   2020-10-19      57

In [67]:
len(covid_death_oct_ninteenth_df)

50

In [68]:
covid_death_oct_ninteenth_df

                      date  deaths
state
Alabama         2020-10-19    2789
Alaska          2020-10-19      63
Arizona         2020-10-19    5830
Arkansas        2020-10-19    1714
California      2020-10-19   16987
Colorado        2020-10-19    2207
Connecticut     2020-10-19    4554
Delaware        2020-10-19     666
Florida         2020-10-19   16020
Georgia         2020-10-19    7479
Hawaii          2020-10-19     186
Idaho           2020-10-19     535
Illinois        2020-10-19    9520
Indiana         2020-10-19    3960
Iowa            2020-10-19    1548
Kansas          2020-10-19     872
Kentucky        2020-10-19    1381
Louisiana       2020-10-19    5766
Maine           2020-10-19     146
Maryland        2020-10-19    4041
Massachusetts   2020-10-19    9753
Michigan        2020-10-19    7364
Minnesota       2020-10-19    2292
Mississippi     2020-10-19    3171
Missouri        2020-10-19    2660
Montana         2020-10-19     242
Nebraska        2020-10-19     568
Nevada          2020-10-19    1714
New Hampshire   2020-10-19     468
New Jersey      2020-10-19   16214
New Mexico      2020-10-19     935
New York        2020-10-19   32990
North Carolina  2020-10-19    3969
North Dakota    2020-10-19     413
Ohio            2020-10-19    5075
Oklahoma        2020-10-19    1173
Oregon          2020-10-19     630
Pennsylvania    2020-10-19    8562
Rhode Island    2020-10-19    1159
South Carolina  2020-10-19    3661
South Dakota    2020-10-19     323
Tennessee       2020-10-19    2896
Texas           2020-10-19   17564
Utah            2020-10-19     547
Vermont         2020-10-19      58
Virginia        2020-10-19    3457
Washington      2020-10-19    2357
West Virginia   2020-10-19     399
Wisconsin       2020-10-19    1624
Wyoming         2020-10-19      57

In [74]:
narrow_total_state_deaths_df = covid_death_oct_ninteenth_df

final_total_death_state_df = narrow_total_state_deaths_df

final_total_death_state_df

                      date  deaths
state
Alabama         2020-10-19    2789
Alaska          2020-10-19      63
Arizona         2020-10-19    5830
Arkansas        2020-10-19    1714
California      2020-10-19   16987
Colorado        2020-10-19    2207
Connecticut     2020-10-19    4554
Delaware        2020-10-19     666
Florida         2020-10-19   16020
Georgia         2020-10-19    7479
Hawaii          2020-10-19     186
Idaho           2020-10-19     535
Illinois        2020-10-19    9520
Indiana         2020-10-19    3960
Iowa            2020-10-19    1548
Kansas          2020-10-19     872
Kentucky        2020-10-19    1381
Louisiana       2020-10-19    5766
Maine           2020-10-19     146
Maryland        2020-10-19    4041
Massachusetts   2020-10-19    9753
Michigan        2020-10-19    7364
Minnesota       2020-10-19    2292
Mississippi     2020-10-19    3171
Missouri        2020-10-19    2660
Montana         2020-10-19     242
Nebraska        2020-10-19     568
Nevada          2020-10-19    1714
New Hampshire   2020-10-19     468
New Jersey      2020-10-19   16214
New Mexico      2020-10-19     935
New York        2020-10-19   32990
North Carolina  2020-10-19    3969
North Dakota    2020-10-19     413
Ohio            2020-10-19    5075
Oklahoma        2020-10-19    1173
Oregon          2020-10-19     630
Pennsylvania    2020-10-19    8562
Rhode Island    2020-10-19    1159
South Carolina  2020-10-19    3661
South Dakota    2020-10-19     323
Tennessee       2020-10-19    2896
Texas           2020-10-19   17564
Utah            2020-10-19     547
Vermont         2020-10-19      58
Virginia        2020-10-19    3457
Washington      2020-10-19    2357
West Virginia   2020-10-19     399
Wisconsin       2020-10-19    1624
Wyoming         2020-10-19      57

In [75]:
final_total_death_state_df.rename(columns = {'deaths':'Total Deaths from January 2020 to October 2020'}, inplace=True)

In [76]:
# Changed column repesenting deaths to Total Deathsn from 01/2020 to 10/2020
final_total_death_state_df

                      date  Total Deaths from January 2020 to October 2020
state
Alabama         2020-10-19                                            2789
Alaska          2020-10-19                                              63
Arizona         2020-10-19                                            5830
Arkansas        2020-10-19                                            1714
California      2020-10-19                                           16987
Colorado        2020-10-19                                            2207
Connecticut     2020-10-19                                            4554
Delaware        2020-10-19                                             666
Florida         2020-10-19                                           16020
Georgia         2020-10-19                                            7479
Hawaii          2020-10-19                                             186
Idaho           2020-10-19                                             535
Illinois        2020-10-19                                            9520
Indiana         2020-10-19                                            3960
Iowa            2020-10-19                                            1548
Kansas          2020-10-19                                             872
Kentucky        2020-10-19                                            1381
Louisiana       2020-10-19                                            5766
Maine           2020-10-19                                             146
Maryland        2020-10-19                                            4041
Massachusetts   2020-10-19                                            9753
Michigan        2020-10-19                                            7364
Minnesota       2020-10-19                                            2292
Mississippi     2020-10-19                                            3171
Missouri        2020-10-19                                            2660
Montana         2020-10-19                                             242
Nebraska        2020-10-19                                             568
Nevada          2020-10-19                                            1714
New Hampshire   2020-10-19                                             468
New Jersey      2020-10-19                                           16214
New Mexico      2020-10-19                                             935
New York        2020-10-19                                           32990
North Carolina  2020-10-19                                            3969
North Dakota    2020-10-19                                             413
Ohio            2020-10-19                                            5075
Oklahoma        2020-10-19                                            1173
Oregon          2020-10-19                                             630
Pennsylvania    2020-10-19                                            8562
Rhode Island    2020-10-19                                            1159
South Carolina  2020-10-19                                            3661
South Dakota    2020-10-19                                             323
Tennessee       2020-10-19                                            2896
Texas           2020-10-19                                           17564
Utah            2020-10-19                                             547
Vermont         2020-10-19                                              58
Virginia        2020-10-19                                            3457
Washington      2020-10-19                                            2357
West Virginia   2020-10-19                                             399
Wisconsin       2020-10-19                                            1624
Wyoming         2020-10-19                                              57

In [3]:
len(final_total_death_state_df)

NameError: name 'final_total_death_state_df' is not defined

In [80]:
# Dropping date column, which was October 19th, 2020. So final df is the total amount of deaths as repoted by
#each state over the period of time begiining 1/21/2020 and endong on 10/19/2020

states_total_deaths = final_total_death_state_df.drop(['date'], axis=1)
states_total_deaths_df = pd.DataFrame(states_total_deaths)
states_total_deaths_df

                Total Deaths from January 2020 to October 2020
state
Alabama                                                   2789
Alaska                                                      63
Arizona                                                   5830
Arkansas                                                  1714
California                                               16987
Colorado                                                  2207
Connecticut                                               4554
Delaware                                                   666
Florida                                                  16020
Georgia                                                   7479
Hawaii                                                     186
Idaho                                                      535
Illinois                                                  9520
Indiana                                                   3960
Iowa                                                      1548
Kansas                                                     872
Kentucky                                                  1381
Louisiana                                                 5766
Maine                                                      146
Maryland                                                  4041
Massachusetts                                             9753
Michigan                                                  7364
Minnesota                                                 2292
Mississippi                                               3171
Missouri                                                  2660
Montana                                                    242
Nebraska                                                   568
Nevada                                                    1714
New Hampshire                                              468
New Jersey                                               16214
New Mexico                                                 935
New York                                                 32990
North Carolina                                            3969
North Dakota                                               413
Ohio                                                      5075
Oklahoma                                                  1173
Oregon                                                     630
Pennsylvania                                              8562
Rhode Island                                              1159
South Carolina                                            3661
South Dakota                                               323
Tennessee                                                 2896
Texas                                                    17564
Utah                                                       547
Vermont                                                     58
Virginia                                                  3457
Washington                                                2357
West Virginia                                              399
Wisconsin                                                 1624
Wyoming                                                     57

In [2]:
len(states_total_deaths_df)

NameError: name 'states_total_deaths_df' is not defined

In [82]:
# The total number of COVID-19 deaths in the United States as of 10/19/2020, with the first data being reported 
# on 1/21/2020
states_total_deaths_df["Total Deaths from January 2020 to October 2020"].sum()

218559

In [4]:
len(states_total_deaths_df)

NameError: name 'states_total_deaths_df' is not defined

In [83]:
output_data = "Resources/final_death_per_state.csv"
states_total_deaths_df.to_csv(output_data)