In [34]:
# Read CSV files from NY Times and covidtracking.com
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
covidtrack_to_load = "Resources/all-states-history 10-20-2020.csv"
NYtimes_to_load = "Resources/data from NYT 10-20-2020.csv"
state_list = "Resources/state list.csv"

# Read Purchasing File and store into Pandas data frame
covidtrack_data = pd.read_csv(covidtrack_to_load)
NYtimes_data = pd.read_csv(NYtimes_to_load)
state_list_data = pd.read_csv(state_list)
state_list_data["state"].value_counts()

Delaware                    1
Maine                       1
Kansas                      1
Nevada                      1
Northern Mariana Islands    1
Puerto Rico                 1
Minnesota                   1
Indiana                     1
Florida                     1
Wyoming                     1
New Hampshire               1
Kentucky                    1
Idaho                       1
District of Columbia        1
U.S. Virgin Islands         1
Colorado                    1
Mississippi                 1
Rhode Island                1
South Carolina              1
Alaska                      1
Illinois                    1
North Carolina              1
American Samoa              1
Tennessee                   1
Ohio                        1
Montana                     1
Arkansas                    1
Virginia                    1
Arizona                     1
Oklahoma                    1
Alabama                     1
Oregon                      1
New York                    1
New Mexico                  1
Maryland                    1
South Dakota                1
North Dakota                1
Texas                       1
Guam                        1
Nebraska                    1
Louisiana                   1
Massachusetts               1
Iowa                        1
West Virginia               1
Wisconsin                   1
California                  1
Pennsylvania                1
Missouri                    1
Washington                  1
Utah                        1
Michigan                    1
Vermont                     1
Hawaii                      1
Georgia                     1
New Jersey                  1
Connecticut                 1
Name: state, dtype: int64

In [101]:
# reduce columns of covidtrack_data
reduced_covidtrack_data = pd.DataFrame(covidtrack_data, columns = ["date", "state", "negative", "negativeIncrease","positive","positiveIncrease","totalTestResults","totalTestResultsIncrease"])
reduced_covidtrack_data["date"]=pd.to_datetime(reduced_covidtrack_data["date"])
reduced_covidtrack_data

,date,state,negative,negativeIncrease,positive,positiveIncrease,totalTestResults,totalTestResultsIncrease
0,2020-10-20,AK,534093.0,10090,12432.0,212,546525.0,10302
1,2020-10-20,AL,1112559.0,4731,174528.0,1043,1265575.0,5475
2,2020-10-20,AR,1137234.0,7110,100441.0,844,1231652.0,7738
3,2020-10-20,AS,1616.0,0,0.0,0,1616.0,0
4,2020-10-20,AZ,1419675.0,6571,232937.0,1040,1647345.0,7560
...,...,...,...,...,...,...,...,...
12928,2020-01-24,WA,0.0,0,0.0,0,0.0,0
12929,2020-01-23,MA,NaN,0,NaN,0,2.0,1
12930,2020-01-23,WA,0.0,0,0.0,0,0.0,0
12931,2020-01-22,MA,NaN,0,NaN,0,1.0,0
12932,2020-01-22,WA,0.0,0,0.0,0,0.0,0

In [102]:
# rename columns of NYtimes_data
rename_NYtimes_data["date"]=pd.to_datetime(rename_NYtimes_data["date"])

In [103]:
new_data= pd.merge(rename_NYtimes_data, state_list_data, on="state",how="left")
final_data = pd.merge(new_data, reduced_covidtrack_data,left_on=["date","initial"],right_on=["date","state"])
# final_data["total count"]=final_data["positive"]+final_data["negative"]
final_data

,date,state_x,fips,positive_x,deaths,initial,state_y,negative,negativeIncrease,positive_y,positiveIncrease,totalTestResults,totalTestResultsIncrease
0,2020-01-22,Washington,53,1,0,WA,WA,0.0,0,0.0,0,0.0,0
1,2020-01-23,Washington,53,1,0,WA,WA,0.0,0,0.0,0,0.0,0
2,2020-01-24,Washington,53,1,0,WA,WA,0.0,0,0.0,0,0.0,0
3,2020-01-25,Washington,53,1,0,WA,WA,0.0,0,0.0,0,0.0,0
4,2020-01-26,Washington,53,1,0,WA,WA,0.0,0,0.0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12332,2020-10-20,Virginia,51,167754,3485,VA,VA,2254727.0,13055,167754.0,926,2411940.0,13829
12333,2020-10-20,Washington,53,103845,2380,WA,WA,2145675.0,13091,98661.0,460,2244336.0,13551
12334,2020-10-20,West Virginia,54,20519,408,WV,WV,671290.0,3593,20519.0,226,691809.0,3819
12335,2020-10-20,Wisconsin,55,187898,1660,WI,WI,1712883.0,9070,187828.0,4686,1900711.0,13756
12336,2020-10-20,Wyoming,56,9526,61,WY,WY,108754.0,0,9526.0,215,118280.0,215

In [95]:
data_group_by = final_data.groupby([final_data['date'].dt.strftime('%B')],final_data["state_x"])["total count"]

df=data_group_by.value_counts()
pd.DataFrame(df)

KeyError: 'states_x'